packages:
  - '.'
nodeLinker: hoisted
publicHoistPattern:
  - '*'
blockExoticSubdeps: false
confirmModulesPurge: false
allowBuilds:
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
