packages:
  - .

allowBuilds:
  '@parcel/watcher': true
  better-sqlite3: true
  electron: true
  electron-winstaller: true
  esbuild: true
  ssh2: true

blockExoticSubdeps: false

# 忽略当前平台不需要的可选原生包，避免下载或编译失败
ignoredOptionalDependencies:
  - cpu-features
  - '@napi-rs/canvas-darwin-arm64'
  - '@napi-rs/canvas-darwin-x64'
  - '@napi-rs/canvas-linux-arm-gnueabihf'
  - '@napi-rs/canvas-linux-arm64-gnu'
  - '@napi-rs/canvas-linux-arm64-musl'
  - '@napi-rs/canvas-linux-riscv64-gnu'
  - '@napi-rs/canvas-linux-x64-gnu'
  - '@napi-rs/canvas-linux-x64-musl'


confirmModulesPurge: false

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@parcel/watcher'
  - better-sqlite3
  - electron
  - electron-winstaller
  - esbuild

publicHoistPattern:
  - '*'
